spring:
  shardingsphere:
    datasource:
      names: master,slave
    master:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      driver-url: jdbc:mysql://localhost:3306/ds1
      username: root
      password: root
    slave1:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      driver-url: jdbc:mysql://localhost:330/ds1
      username: root
      password: root

---
spring:
  shardingsphere:
    rules:
      readwrite-splitting:
        data-sources:
          # rs是由我们定义的RWS规则名称
          !readwrite_ds:
            static:
              write-data-source-name:

            type: Static
            props:



